### ISSUE TITLE
Cyrillic characters are not recognized

### ISSUE THREAD

**Issue by GrayWolfson** [ai25395/FMatPix#1]
Hi
Using the formula below as an example
[https://filestore.community.support.microsoft.com/api/images/3004665f-3c2c-408d-92e1-67a1acda7a57?upload=true](https://filestore.community.support.microsoft.com/api/images/3004665f-3c2c-408d-92e1-67a1acda7a57?upload=true)

Cyrillic characters are not recognized.
c_{\mathrm{p}\mathrm{i}}=\frac{(\mathrm{h}_{\mathrm{cr}}^{B O A}-\mathrm{h}_{\mathrm{i}}^{B O A})}{(\mathrm{h}_{\mathrm{cr}}^{B O A}-\mathrm{h}_{1}^{B O A})_{\alpha=0}}

![изображение](https://github.com/user-attachments/assets/658a088a-df1e-4a18-92e6-7828fc211af7)

c_{\mathrm{p}\mathrm{i}}=\frac{(\mathrm{h}_{\mathrm{cr}}^{B O A}-\mathrm{h}_{\mathrm{i}}^{B O A})}{(\mathrm{h}_{\mathrm{cr}}^{B O A}-\mathrm{h}_{1}^{B O A})_{\alpha=0}}

Ideally there should be

c_{\mathrm{p}\mathrm{i}}=\frac{(\mathrm{h}_{\mathrm{ст}}^{ВОД}-\mathrm{h}_{\mathrm{i}}^{ВОД})}{(\mathrm{h}_{\mathrm{ст}}^{ВОД}-\mathrm{h}_{1}^{ВОД})_{\alpha=0}}

**Comment by ai25395** [comment]
Yes, it does have bad support for Cyrillic letters. This is mainly due to the lack of Cyrillic alphabet in the training set of the recognition model. This needs to be improved by expanding the training set and retraining the network.

**Comment by ai25395** [comment]
The recognition models I use are open source based on transformer arch, so they usually have a file called like tokenizer.json specifying what characters the model should learn to recognize. As far as I know, the tokenizer.json of the mainstream models does not contain the Cyrillic alphabet, which is why they are not recognized.
