### ISSUE TITLE
第一次能使用，后面就不行了

### ISSUE THREAD

**Issue by hanvegh** [ai25395/FMatPix#11]
alt+q 截图，能在history中看到记录，但是复制不了（无论是左击还是右击），无论是记事本还是mathtype都不能显示出来，已重启软件（软件安装在D盘）。
![image](https://github.com/user-attachments/assets/1fa85675-f5de-4ded-852c-781832ef53eb)

安装的是您发布的最新版本。

**Comment by hanvegh** [comment]
多尝试几次就好了，很随机

**Comment by ai25395** [comment]
可能是识别失败了
