### ISSUE TITLE
有没有可能自定义快捷键，或者有个截图按钮呢？

### ISSUE THREAD

**Issue by htyxyt** [ai25395/FMatPix#4]
如题

**Comment by ai25395** [comment]
关于自定义按键，可以看下readme后面的FAQ。
截图按钮早期版本有，后来考虑到用快捷键方便很多，就去掉按钮了，毕竟如果在做公式编辑或写文章，应该都会有键盘吧；如果您有什么特殊原因，可以说一下，也许是我考虑不周。

**Comment by htyxyt** [comment]
> 关于自定义按键，可以看下readme后面的FAQ。 截图按钮早期版本有，后来考虑到用快捷键方便很多，就去掉按钮了，毕竟如果在做公式编辑或写文章，应该都会有键盘吧；如果您有什么特殊原因，可以说一下，也许是我考虑不周。

快捷键问题get。对于按钮，键盘党没问题，但可以鼠标操作也是多一种选择嘛，毕竟有人在mathtype中也是点点点。
