### ISSUE TITLE
没有复制进剪贴板

### ISSUE THREAD

**Issue by hualaobisi** [ai25395/FMatPix#5]
截图识别是有了，历史里有识别的公式的，但是无论是点击Copy MathMi还是在历史里右键单击图片都没有用，剪贴板是空白的是我电脑设置的原因吗?
![屏幕截图 2024-11-06 212934](https://github.com/user-attachments/assets/3bd51782-ed4b-4112-b381-9dcef6d596b1)

**Comment by Integrity-zz** [comment]
请问Page Ocr模式识别不出来的公式怎么办呢，单独选中也识别不出来

**Comment by hualaobisi** [comment]
> 没有复制进剪切板，但是在历史里有，这种情况一般是有些公式识别错误，导致识别内容为“”，导致不能复制到剪切板。你可以多试几个公式，看看是否都这样。另外，试试Page Ocr，如果Page Ocr用红框显示出了公式，但点击后还是不能复制，那应该就是软件之外的问题了，比如电脑设置问题。

好像找到原因了，因为我电脑设置是深色模式，背景是黑的情况下，有时候是识别不出来，换了白色背景就好了。
