### ISSUE TITLE
截图后history能看到但是不闪红灯不识别

### ISSUE THREAD

**Issue by Yaolab-fantastic** [ai25395/FMatPix#6]
只有第一次可以识别，接下来截图识别失败，不闪红灯只有绿灯常亮。history可以看到，但是复制无效

**Comment by ai25395** [comment]
不知道你是否解决了。有截图但绿灯常亮，说明识别过程中发生了错误，但这种情况一般出现在个别公式上。如果只是个别公式不能识别，属于正常情况。
