### ISSUE TITLE
报告3个bug

### ISSUE THREAD

**Issue by zhaosj98** [ai25395/FMatPix#8]
1. 复制MathML粘贴到word里面不会变成公式，而是xml代码

例如：
```xml
<math>
<mrow><mi>x</mi><mo>=</mo></mrow><mrow><mi>x</mi><mo>+</mo></mrow><mrow><mn>1</mn></mrow></math>
```
粘贴到word里面是：
![image](https://github.com/user-attachments/assets/c4d0019c-f2d1-4c1c-a298-8ca1201d60d0)
但是我对比同类软件，他们会在math标签的开头加上`xmlns="http://www.w3.org/1998/Math/MathML"`，例如：

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>x</mi>
  <mo>=</mo>
  <mi>x</mi>
  <mo>+</mo>
  <mn>1</mn>
</math>
```

然后粘贴到word里面就变成公式了：
![image](https://github.com/user-attachments/assets/29e75eb3-4afd-4470-8627-3aeb33824258)
希望可以在软件里面复制mathml的时候加上`xmlns="http://www.w3.org/1998/Math/MathML"`

---

2. 历史记录窗口处于打开状态时，截图识别新的公式，不会自动更新历史记录，而是需要关闭窗口重新打开

---

3. 另外还有一个识别优化的问题，截图识别一些很短的公式时，如果紧挨着截图就会导致识别失败，如果把周围的空白也截图进来就会识别成功
识别失败的图片：
![image](https://github.com/user-attachments/assets/46a344b1-2cd6-42ca-82a5-27f8983a68b2)
识别成功的图片：
![image](https://github.com/user-attachments/assets/d4f25dac-685e-44c8-a602-a3161e10ea56)

**Comment by ai25395** [comment]
感谢您的使用反馈。
bug1将在下个版本修复；
bug3，将从模型的训练和使用角度尝试修复；
2其实不能算bug，考虑作为一个new feature加入后续版本。
